# Generated by Django 5.1.6 on 2025-02-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
