# Generated by Django 5.1.6 on 2025-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='estimated_yearly_sales',
            field=models.IntegerField(),
        ),
    ]
