# Generated by Django 5.1.6 on 2025-02-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_customer_estimated_yearly_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(choices=[('mass_market', 'Mass Market'), ('mm2', 'MM2'), ('ecommerce', 'Ecommerce'), ('wholesale', 'Wholesale'), ('international', 'International')], default='mass_market', max_length=20),
        ),
    ]
