# Generated by Django 5.1.6 on 2025-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_address_contact_birthday_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthday_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='birthday_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='relationship_score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
    ]
