# Generated by Django 5.1.6 on 2025-03-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_contact_created_at_contact_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='relationship_score',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Salesperson', 'Salesperson'), ('Manager - Mass Market', 'Manager - Mass Market'), ('Manager - MM2', 'Manager - MM2'), ('Manager - Ecommerce', 'Manager - Ecommerce'), ('Manager - Wholesale', 'Manager - Wholesale')], default='Salesperson', max_length=30),
        ),
    ]
