# Generated by Django 5.1.6 on 2025-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_gift_giftseason_giftassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftseason',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='giftseason',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
