# Generated by Django 5.1.6 on 2025-03-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_giftseason_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftseason',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='giftseason',
            name='start_date',
        ),
        migrations.AddField(
            model_name='giftseason',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
