# Generated by Django 5.1.6 on 2025-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_giftseason_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftassignment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
